rubyパートできました
dai65527/ft_reloaded_preopen00 pull request #2
Opened 2021-02-05 07:09 UTC by dai65527

rubyの方できました。一応pull request出しておきますが、明日夜ontimeレビューしましょう！

2021-02-05 10:56 UTC, sho-yoshikawa requested changes
お互い頑張りましょう！

2021-02-05 10:56 UTC, sho-yoshikawa commented on ex00/var.rb
> +  puts "#{ft_fixnum} is type of #{ft_fixnum.class}"
Integerは環境依存。

2021-02-05 10:56 UTC, sho-yoshikawa commented on ex04/state.rb
> +if ARGV.length() != 1 then
if文のthenの削除。

2021-02-05 10:56 UTC, sho-yoshikawa commented on ex05/all_in.rb
> +if ARGV.length() != 1 then
if文のthenの削除。

2021-02-05 10:56 UTC, sho-yoshikawa commented on ex05/all_in.rb
> +  capitalized_key = key.split(" ").map(&:capitalize).join(" ");
35-37の書き方を41行目に統一。ex):&strip

2021-02-05 10:56 UTC, sho-yoshikawa commented on ex06/my_sort.rb
> +  puts "#{data[0]}: #{data[1]}"
data[0](name)のみの出力が正しいと思います。

2021-02-06 09:39 UTC, dai65527 commented
修正したので確認お願いします！

2021-02-06 11:57 UTC, sho-yoshikawa commented
問題ないと思います！

2021-02-06 12:33 UTC, merged